config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  get 'password_resets/edit'

  devise_for :users
  resources :publishers
  resources :author
  resources :categories
  resources :books
  resources :about
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  root 'welcomes#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
    belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
   devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable
   has_many :books
   attr_accessor :remember_token, :activation_token, :reset_token
   
   def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
   end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
        @page_title = 'About Us';
    end 
end

    

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def destroy
  end

  def edit
  end

  def index
  end

  def show
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def destroy
  end

  def edit
  end

  def index
  end

  def show
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  def new
     @book = current_user.books.build
  end

  def create
     @book = current_user.books.build(book_params)
      if @book.save
        redirect_to @book, notice: 'Book was successfully created.' 
      else
        render action: 'new'
      end
  end

  def update
      if @book.update(book_params)
        redirect_to @book, notice: 'Book was successfully updated.' 
      else
        render action: 'edit'
      end
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def destroy
    Book.find(params[:id]).destroy
    flash[:success] = "Book deleted"
    redirect_to books_url
  end

  def index
    @book = Book.all.order("created_at DESC")
  end


  def show
    @book = Book.find(params[:id])
  end
end

private
  
  def set_book
      @book = Book.find_by(id: params[:id])
  end

  def book_params
      params.require(:book).permit(:description, :title)
  end

  def correct_user
      @book = current_user.books.find_by(id: params[:id])
      redirect_to books_path, notice: "Not authorized to edit this plan" if @book.nil?
  end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def destroy
  end

  def edit
  end

  def index
  end

  def show
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def edit
  end
  
  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Email sent with password reset instructions"
      redirect_to root_url
    else
      flash.now[:danger] = "Email address not found"
      render 'new'
    end
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def destroy
  end

  def edit
  end

  def index
  end

  def show
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/author/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/author/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/author/edit.html.erb
<h1>Authors#edit</h1>
<p>Find me in app/views/authors/edit.html.erb</p>

app/views/author/index.html.erb
<h1>Authors#index</h1>
<p>Find me in app/views/authors/index.html.erb</p>

app/views/author/new.html.erb
<h1>Authors#new</h1>
<p>Find me in app/views/authors/new.html.erb</p>

app/views/author/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/author/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Get Nerdy</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%=link_to "About", about_index_url%></li>
        <li><%=link_to "Books", new_book_path %></li>
        <li><%=link_to "Authors", new_author_path %></li>
        <li><%=link_to "Category", new_category_path %></li>

app/views/books/create.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h2>Add a Book to the Repository</h2></div>
   <div class="panel-body">
    <%= form_for Book.new do |f| %>
            <div class= "form group">
                 <%= f.label :title %> </br>
                 <%= f.text_field :title , autofocus: true, class: "form control" %></br>
                 <%= f.label :description %> </br>
                 <%= f.text_area:description ,autofocus: true, class: "form control"%>
                 <%= f.submit "Create"%>
            </div>
     <%end%>
     </div>   
   </div>
 </div>
 

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h2>Edit the novel in which you created</h2></div>
   <div class="panel-body">
     <%= form_for @book do |f| %> 
           <div class= "form group">
               <%= f.label :title %> 
               <%= f.text_field :title , autofocus: true, class: "form control" %></br>
       
               <%= f.label :description %>
               <%= f.text_area:description ,autofocus: true, class: "form control"%>
            </div>  
             <div class="actions">
              <%= f.submit "Edit", class:"btn btn-success" %>
             </div>
      <%end%>
     </div>   
   </div>
 </div>

app/views/books/index.html.erb
  <% @book.each do |book| %>
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <div class="panel panel-default">
        <div class= "panel-heading center">
          <div class="panel-body">
              <strong><%= book.title %></strong></br>
              <%= book.description %></br>
              <%= link_to 'Edit', edit_book_path(book) %> |
              <%= link_to 'Back', books_path %> |
              <%= link_to 'Delete',book, method: :delete, data: { confirm: "You sure?" } %>
          </div>
        </div>
       </div>
     </div>
  </div>
<% end %>

app/views/books/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h2>Add a Book to the Repository</h2></div>
   <div class="panel-body">
     <%= form_for Book.new do |f| %>
           <div class= "form group">
               <%= f.label :title, class: "col-xs-12 col-md-1" %> 
               <%= f.text_field :title , autofocus: true, class: "form control",  :size => "51.5" %>
           </div>
           </br>
           <div class= "form group">
               <%= f.label :description, class: "col-xs-12 col-md-1" %>
               <%= f.text_area :description , autofocus: true, class: "form control",  :cols => "50", :rows => "10"%>
            </div>  
             <div class="actions">
              <%= f.submit "Create", class:"btn btn-success" %>
             </div>
      <%end%>
     </div>   
   </div> 
 </div>

app/views/books/show.html.erb
  <div class="row">
  <div class="col-md-offset-2 col-md-8">
  <div class="panel panel-default">
  <div class= "panel-heading center">
  <div class="panel-body">
  <strong><%= @book.title %></strong></br>
  <%= @book.description %></br>
  <%= link_to 'Edit', edit_book_path(@book) %> |
  <%= link_to 'Back', books_path %> 
  </div>
  </div>
  </div>
  </div>
  </div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

app/views/publishers/edit.html.erb
<h1>Publishers#edit</h1>
<p>Find me in app/views/publishers/edit.html.erb</p>

app/views/publishers/index.html.erb
<h1>Publishers#index</h1>
<p>Find me in app/views/publishers/index.html.erb</p>

app/views/publishers/new.html.erb
<h1>Publishers#new</h1>
<p>Find me in app/views/publishers/new.html.erb</p>

app/views/publishers/show.html.erb
<h1>Publishers#show</h1>
<p>Find me in app/views/publishers/show.html.erb</p>

app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>

app/views/welcomes/_header.html.erb
    <!-- Collect the nav links, forms, and other content for toggling -->
  <nav>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About me', home_about_path %></li> 
        
            <% if user_signed_in? %>
               <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %><li>
               <li><%= link_to 'Edit Profile',  edit_user_registration_path %></li>
               <li><%= link_to 'All Pins',  pins_path  %></li> 
               <li><%= link_to 'New Pin',   new_pin_path %></li> 
              
           <% else %>
               <li><%= link_to 'Login', new_user_session_path %><li>
               <li><%= link_to 'Signup',  new_user_registration_path %></li>
            <% end %>
              
      </ul>
    </div><!-- /.navbar-collapse --><!-- /.container-fluid -->
</nav>

app/views/welcomes/_welcome.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    <ul>
     
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
      <%=link_to "Get Nerdy", books_path,class: 'btn btn-primary' %>
      <%=link_to "About", about_index_url, class: 'btn btn-primary'%>
      
      <% if user_signed_in? %>
        
          <%=link_to "Add a New Book", new_book_path, class: 'btn btn-info'%>
          <%=link_to 'All Nerdy Books',books_path, class: 'btn btn-success'%>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-success' %>
          <%=link_to "Forgot password",   new_password_reset_path, class: 'btn btn-success' %>
        <%else%>
          <%=link_to "Sign up", new_user_registration_path, class: 'btn btn-success' %>
          <%=link_to "Sign in", user_session_path, class: 'btn btn-success' %>
         <%end%>
      </ul>
      </button>
    </div><!-- /.navbar-collapse -->
  </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/welcomes/index.html.erb
<div class="jumbotron">   
     <div class= 'container text-center'>
        <h1>Welcome to the Nerdy Book Repository</h1>
            <p>Where nerds can get their geek on.</p>
            <p>Checkout our nerdy book submissions <%=link_to 'here',books_path%></p>
    </div>
</div>